package behavior.alignment.analysis;
import behavior.alignment.profile.*;import behavior.evidence.casefile.*;import behavior.expected.profile.*;import coinProperties.Currency;import operationalControl.profile.ProfessionCreditProfile;import java.time.temporal.ChronoUnit;import java.util.*;
/** Builds exhaustive institutional compatibility maps without scores, ranking or inspection semantics. */
public final class StructuralAlignmentAnalyzer{
 private static final Map<Currency,Long> VALUE=Map.of(Currency.VALERITA,1L,Currency.SUELDO,1_000L,Currency.BERYLARE,210_000L,Currency.REAL_A5,420_000L);
 public StructuralAlignmentAnalysisReport analyze(Collection<BehaviorEvidenceSet> cases,Collection<ProfessionCreditProfile> profiles){Objects.requireNonNull(cases);Objects.requireNonNull(profiles);List<CreditProfileDescriptor> descriptors=profiles.stream().map(CreditProfileDescriptor::from).sorted(Comparator.comparing(CreditProfileDescriptor::profession)).toList();List<StructuralAlignment> out=new ArrayList<>();long comparisons=0,compatible=0,cross=0,missing=0;
  for(BehaviorEvidenceSet set:cases){LinkedHashMap<String,ProfileCompatibility> map=new LinkedHashMap<>();for(CreditProfileDescriptor descriptor:descriptors){ProfileCompatibility result=compare(set,descriptor);map.put(descriptor.profession(),result);comparisons++;if(result.compatible()){compatible++;if(!descriptor.profession().equals(set.profession().name()))cross++;}}if(!map.containsKey(set.profession().name()))missing++;out.add(new StructuralAlignment(StructuralAlignmentId.from(set.id()),set.id(),set.consumerId(),set.profession(),set.seasonPeriod(),map));}
  return new StructuralAlignmentAnalysisReport(cases.size(),out.size(),comparisons,compatible,cross,missing,out);
 }
 private ProfileCompatibility compare(BehaviorEvidenceSet set,CreditProfileDescriptor p){EnumMap<CreditProfileDimension,DimensionCompatibility> dims=new EnumMap<>(CreditProfileDimension.class);List<String> why=new ArrayList<>();if(p.unlimited()){for(CreditProfileDimension d:CreditProfileDimension.values())dims.put(d,DimensionCompatibility.COMPATIBLE);why.add("Perfil institucional ilimitado");return new ProfileCompatibility(p,dims,why);}long days=ChronoUnit.DAYS.between(set.seasonPeriod().startsOn(),set.seasonPeriod().endsOn())+1;
  OptionalDouble activity=observed(set,ExpectedBehaviorMetricFamily.SEASON_ACTIVITY_TOTAL,m->m.subject().equals("ALL"));if(activity.isPresent()){double limit=(double)p.dailyInteractionCount()*days;put(dims,why,CreditProfileDimension.SEASON_INTERACTION_CAPACITY,activity.getAsDouble()<=limit,"actividad observada="+activity.getAsDouble()+", capacidad estacional="+limit);}else dims.put(CreditProfileDimension.SEASON_INTERACTION_CAPACITY,DimensionCompatibility.UNOBSERVED);
  double monetary=categoryMoneyInValeritas(set);boolean moneyObserved=hasFamily(set,ExpectedBehaviorMetricFamily.CATEGORY_MONETARY_VOLUME);if(moneyObserved){double limit=p.monthlyEconomicCapacity()*(days/30d);put(dims,why,CreditProfileDimension.SEASON_MONETARY_CAPACITY,monetary<=limit,"volumen observado="+monetary+", capacidad estacional="+limit);}else dims.put(CreditProfileDimension.SEASON_MONETARY_CAPACITY,DimensionCompatibility.UNOBSERVED);
  Optional<Currency> highestPurchase=highestCurrency(set,Set.of(ExpectedBehaviorMetricFamily.CATEGORY_MONETARY_VOLUME,ExpectedBehaviorMetricFamily.CONSUMABLE_MONETARY_VOLUME));if(highestPurchase.isPresent())put(dims,why,CreditProfileDimension.PURCHASE_CURRENCY_CEILING,rank(highestPurchase.get())<=rank(p.maximumPurchaseCurrency()),"moneda máxima observada="+highestPurchase.get()+", techo="+p.maximumPurchaseCurrency());else dims.put(CreditProfileDimension.PURCHASE_CURRENCY_CEILING,DimensionCompatibility.UNOBSERVED);
  dims.put(CreditProfileDimension.OBSERVED_OPERATION_CURRENCY_CEILINGS,DimensionCompatibility.UNOBSERVED);why.add("Los eventos M3.3 no conservan volumen monetario por acuñación, cambio o transferencia");
  dims.put(CreditProfileDimension.CONSUMABLE_ACCESS_CEILING,DimensionCompatibility.UNOBSERVED);why.add("Las categorías conductuales no codifican todavía el tipo crediticio BASIC_NECESSITY/SOCIAL_UTILITY/PRIVATE_USE");
  return new ProfileCompatibility(p,dims,why);
 }
 private static void put(Map<CreditProfileDimension,DimensionCompatibility>d,List<String>w,CreditProfileDimension k,boolean ok,String text){d.put(k,ok?DimensionCompatibility.COMPATIBLE:DimensionCompatibility.INCOMPATIBLE);w.add(k+": "+text);}
 private static OptionalDouble observed(BehaviorEvidenceSet s,ExpectedBehaviorMetricFamily f,java.util.function.Predicate<ExpectedBehaviorMetric> predicate){return s.allEvidence().stream().filter(e->e.metric().family()==f&&predicate.test(e.metric())).mapToDouble(e->e.deviation().observedValue()).findFirst();}
 private static boolean hasFamily(BehaviorEvidenceSet s,ExpectedBehaviorMetricFamily f){return s.allEvidence().stream().anyMatch(e->e.metric().family()==f);}
 private static double categoryMoneyInValeritas(BehaviorEvidenceSet s){return s.allEvidence().stream().filter(e->e.metric().family()==ExpectedBehaviorMetricFamily.CATEGORY_MONETARY_VOLUME).mapToDouble(e->e.deviation().observedValue()*VALUE.get(e.metric().currency().orElseThrow())).sum();}
 private static Optional<Currency> highestCurrency(BehaviorEvidenceSet s,Set<ExpectedBehaviorMetricFamily> families){return s.allEvidence().stream().map(BehaviorEvidence::metric).filter(m->families.contains(m.family())).flatMap(m->m.currency().stream()).max(Comparator.comparingInt(StructuralAlignmentAnalyzer::rank));}
 private static int rank(Currency c){return switch(c){case VALERITA->0;case SUELDO->1;case BERYLARE->2;case REAL_A5->3;};}
}
