package consumableRegistry;

public enum CommercialTransactionRejectionReason {
    NON_POSITIVE_PRICE,
    CURRENCY_NOT_ALLOWED_FOR_CONSUMABLE_TYPE,
    INSUFFICIENT_BUYER_BALANCE,
    SAME_BUYER_AND_SELLER_ACCOUNT,
    BUYER_ACCOUNT_NOT_OPERATIONAL,
    SELLER_ACCOUNT_NOT_OPERATIONAL,
    BUYER_OPERATIONAL_LIMIT_EXCEEDED,
    SELLER_OPERATIONAL_LIMIT_EXCEEDED
}
