package transfer;

public enum TransferRejectionReason {
    SOURCE_CONSUMER_NOT_FOUND,
    DESTINATION_CONSUMER_NOT_FOUND,
    SAME_SOURCE_AND_DESTINATION_ACCOUNT,
    NON_POSITIVE_QUANTITY,
    INSUFFICIENT_BALANCE,
    SOURCE_ACCOUNT_NOT_OPERATIONAL,
    DESTINATION_ACCOUNT_NOT_OPERATIONAL,
    SOURCE_OPERATIONAL_LIMIT_EXCEEDED,
    DESTINATION_OPERATIONAL_LIMIT_EXCEEDED
}
