package behavior.expected.profile;

/** Canonical families of collective, descriptive behavior metrics. */
public enum ExpectedBehaviorMetricFamily {
    SEASON_ACTIVITY_TOTAL,
    DAY_PERIOD_ACTIVITY,
    EVENT_COUNT,
    EVENT_FREQUENCY,
    CONSUMABLE_PURCHASE_COUNT,
    CONSUMABLE_PURCHASE_FREQUENCY,
    CONSUMABLE_UNIT_COUNT,
    CONSUMABLE_UNIT_FREQUENCY,
    CATEGORY_PURCHASE_COUNT,
    CATEGORY_PURCHASE_FREQUENCY,
    CATEGORY_UNIT_COUNT,
    CATEGORY_UNIT_FREQUENCY,
    CONSUMABLE_MONETARY_VOLUME,
    CONSUMABLE_MONETARY_VOLUME_FREQUENCY,
    CATEGORY_MONETARY_VOLUME,
    CATEGORY_MONETARY_VOLUME_FREQUENCY,
    COUNTERPARTY_COUNT,
    TRANSFERS_SENT,
    TRANSFERS_RECEIVED
}
