package exchangeCoin;

public enum ExchangeRejectionReason {
    NON_POSITIVE_QUANTITY,
    SAME_SOURCE_AND_TARGET_CURRENCY,
    EXCHANGE_ROUTE_NOT_ALLOWED,
    QUANTITY_NOT_EXACTLY_CONVERTIBLE,
    INSUFFICIENT_BALANCE,
    ACCOUNT_NOT_OPERATIONAL,
    OPERATIONAL_LIMIT_EXCEEDED
}
